### ISSUE TITLE
Do not assign a prodcut

### ISSUE THREAD

**Issue by lucianoacsilva** [worldsibu/convector-example-marketplace#2]
Hello,

When I run the command npm run cc:invoke -- org1 -u user1 product init '{"id":"1","name":"Bananas","pictureUrl":"http://example.com/bananas.jpg","description":"Bananas","price":100}' to insert a new product, it throws an error related with a UnhandledPromiseRejectionWarning:

(node:15700) UnhandledPromiseRejectionWarning: Error: Cannot save null userContext.
    at Promise (/home/luciano/convector-example-marketplace/node_modules/fabric-client/lib/Client.js:1441:12)
    at new Promise (<anonymous>)
    at Client.setUserContext (/home/luciano/convector-example-marketplace/node_modules/fabric-client/lib/Client.js:1413:10)
    at Manager.<anonymous> (/home/luciano/convector-example-marketplace/node_modules/@worldsibu/convector-tool-chaincode-manager/node_modules/@worldsibu/convector-common-fabric-helper/dist/src/client.helper.js:126:48)
    at step (/home/luciano/convector-example-marketplace/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/luciano/convector-example-marketplace/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/home/luciano/convector-example-marketplace/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
(node:15700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:15700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Do you guys imagine what could be the issue on this step?

**Comment by walmon** [comment]
`Cannot save null userContext.` is that it is not finding the credentials. What were the previous steps that you performed?

If you are mixing this old example with a Hurley-generated network, it won't find the credentials because paths are in different places...

**Comment by lucianoacsilva** [comment]
Hello, @walmon ,

Yes, I've followed the steps as shown in the tutorial. However, when I tried to reconfigure the network on the blockchain with **npm run restart**, it did not work: it claimed the parenthesis after the declaration of the functions in **init.sh** were not correct. Instead of **npm run restart**, I've set up with **npm run start**.
Besides this, I've followed the other steps as described in the Markdown file.

**Comment by lucianoacsilva** [comment]
And, no, I did not use Hurley when executing this sample project.

**Comment by walmon** [comment]
What OS are you using? Could you check the link I posted on the other issue
you created in this same project?

**Comment by lucianoacsilva** [comment]
Ubuntu 16.04 LTS. On a Virtual Machine.
